### ISSUE TITLE
Undeclared identifier `C_icon_stax_64`

### ISSUE THREAD

**Issue by soulmachine** [Zondax/ledger-zxlib#85]
This is more like a question instead of an issue.

The variable `C_icon_stax_64` used by this line https://github.com/Zondax/ledger-zxlib/blob/361c6918916e183e003eef6f3efc1c7c43f1335b/app/ui/view_stax.c#L339 is not defined anywhere, thus the compiler always throws out the error:

```
use of undeclared identifier 'C_icon_stax_64'
```

Any ideas? Thanks

:link: [zboto Link](https://app.clickup.com/t/8677ype9j)

**Comment by carlosala** [comment]
You need to add stax icons to app/glyphs directory, and in the compilation process it's going to generate needed files. See https://github.com/Zondax/ledger-icp as an example.
