### ISSUE TITLE
Broken build for ledger-kusama

### ISSUE THREAD

**Issue by rllola** [Zondax/ledger-zxlib#9]
Using the current `master` branch seems to break the zemu tests.

The error:
```
launcher: failed to emulate syscall 0x600070c5
vnc_server: readall: connection closed
```

Going back one commit, it works without problem.

This has been seen i when running zemu test in ledger-kusama repo.

**Comment by jleni** [comment]
Ok, that's interesting! in speculos code we should we able to find what 0x600070c5 is

**Comment by jleni** [comment]
it seems here:
https://github.com/LedgerHQ/speculos/blob/239171e29a831fe601f6968b7dd34bccc60d818a/sdk/bolos_syscalls_1.6.h#L224

**Comment by jleni** [comment]
that is strange... SYSCALL_os_setting_get_ID_IN

**Comment by rllola** [comment]
Same for ledger-polkadot...

I m not sure how to fix this. Do we need to update speculos emulator ?

**Comment by rllola** [comment]
Well it seems to work fine if I build the app using `make buildS` instead of just `make`.

**Comment by rllola** [comment]
Closing this.
What was happening is that `make` built both nano s and nano x but the nano x version was replacing the nano s version and I didn't see it.

Maybe we could have a `verbose` mode. It would help to have a better view of what is being build and the `verbose` mode would be use for debugging the script.
